spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: format-transformer
#          uri: format-transformer-service.ft-backend.svc.cluster.local:8080
          uri: http://${FORMAT_TRANSFORMER_HOST}:${FORMAT_TRANSFORMER_PORT}
          predicates:
            - Path=/api/v1/transformation, /api/v1/activity
        - id: format-transformer-stats
#          uri: format-transformer-stats-service.ft-backend.svc.cluster.local:8080
          uri: http://${FORMAT_TRANSFORMER_STATS_HOST}:${FORMAT_TRANSFORMER_STATS_PORT}
          predicates:
            - Path=/api/v1/stats
server:
  port: 8080

