spring:
  application:
    name: gateway-service
  cloud:
    gateway:
        httpclient:
          wiretap: true
        httpserver:
          wiretap: true
        default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
        routes:
         - id: format-transformer
           uri: http://localhost:7000
           predicates:
           - Path=/api/v1/transformation, /api/v1/activity
         - id: format-transformer-stats
           uri: http://localhost:7002
           predicates:
           - Path=/api/v1/stats
server:
  port: 7003

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE